##############################################################################
# COPYRIGHT(C)	: Samsung Electronics Co.Ltd, 2006-2011 ALL RIGHTS RESERVED
#                 Makefile for ISDB-T for TSIF Driver
##############################################################################
# VERSION&DATE	: Version 0.1
##############################################################################

obj-$(CONFIG_FIH_TSIF) += fih_tsif.o

obj-$(CONFIG_TSIF_NM32X_62X_DEV) += nm32x_62x-tsi.o


