
obj-y += dummy.o

obj-y += dynloader/
obj-$(CONFIG_FIH_CAM) += media/
obj-$(CONFIG_FIH_LED) += leds/
obj-$(CONFIG_FIH_KEYPAD) += keyboard/
obj-$(CONFIG_FIH_SENSORS) += sensors/
obj-$(CONFIG_FIH_LCM) += video/
#obj-$(CONFIG_FIH_USB) += usb/
obj-$(CONFIG_FIH_TOUCHSCREEN) += touchscreen/
obj-$(CONFIG_FIH_GPS) += gps/
obj-$(CONFIG_BT_MSM_SLEEP) += bluetooth/
obj-$(CONFIG_FIH_BATTERY) += battery/
obj-$(CONFIG_FIH_NFC) += nfc/
obj-y				+= char/
obj-$(CONFIG_FIH_TSIF) += nmi/nmi625/
obj-$(CONFIG_FIH_TSIF) += misc/
# FIH, CHHsieh, 2011/10/20
# get nand info. form share memory
obj-$(CONFIG_MTD) += mtd/
# FIH, CHHsieh, 2011/10/20
obj-y += cpufreq/
