#
# Copyright (c) 2010 Yamaha Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.
#

obj-$(CONFIG_SENSETEK_I2C_SENSORS)	+= SenseTek_proximity/
obj-$(CONFIG_INPUT_ACCELEROMETER) 	+= accelerometer/
obj-$(CONFIG_INPUT_GEOMAGNETIC) 	+= geomagnetic/
obj-$(CONFIG_INPUT_GYROSCOPE) 		+= gyroscope/
obj-$(CONFIG_INPUT_LIGHT) 		+= light/
obj-$(CONFIG_INPUT_ORIENTATION_YAMAHA) 	+= orientation/
obj-$(CONFIG_INPUT_PRESSURE) 		+= pressure/
obj-$(CONFIG_INPUT_PROXIMITY) 		+= proximity/
obj-$(CONFIG_INPUT_TEMPERATURE) 	+= temperature/
obj-$(CONFIG_INPUT_LPSENSOR)     	+= lightproxisensor/


