obj-$(CONFIG_MSM_CAMERA_FLASH) += flash.o
obj-$(CONFIG_MT9E013) += mt9e013.o mt9e013_reg.o
obj-$(CONFIG_MT9V115) += mt9v115.o
obj-$(CONFIG_FIH_OV5640AF) += ov5640af.o
obj-$(CONFIG_FIH_MT9E013_R180) += mt9e013_r180.o mt9e013_reg_r180.o
obj-$(CONFIG_FIH_OV7692) += ov7692.o
