obj-$(CONFIG_MSM_PROC_COMM)			+= fih_proc_comm.o
obj-$(CONFIG_MSM_PROC_COMM)			+= fih_proc_smdm.o
obj-$(CONFIG_MSM_SMD)				+= fih_smd.o
obj-$(CONFIG_I2C_QUP)				+= i2c_dbg.o
ifndef CONFIG_ARCH_MSM8X60
	obj-$(CONFIG_MSM_ONCRPCROUTER)	+= fih_rpc_hsusb.o
endif

# FIH, CHHsieh, 2011/09/27 {
# setup fver for auto-pack
obj-$(CONFIG_FIH_FXX)				+= fih_fver.o
# FIH, CHHsieh, 2011/09/27 }

# FIH, CHHsieh, 2011/09/27 {
# FTM SIM Test
obj-$(CONFIG_FIH_FTM)				+= ftm_phone.o
# FIH, CHHsieh, 2011/09/27 }

