
obj-$(CONFIG_FIH_FXX)  += ftmgpio.o
obj-$(CONFIG_DIAG_CHAR)         += diag/

#---------------------------------------------
# Provide a char type driver of smd for FTM to communicate with modem.
# Added by Lo, Chien Chung (Paul Lo). 2009/06/16
obj-$(CONFIG_FTM_SMD) += ftm_smd/
#--------------------------------------------

