#
# Makefile for the BROANDCOM BCM4330 device drivers.
#
obj-$(CONFIG_BROADCOM_BCM4330)              		+= bcm4330_bt_power.o bcm4330_wlan_power.o
obj-$(CONFIG_BROADCOM_BCM4330_BLUETOOTH_POWER)      += bcm4330_fm_power.o
obj-$(CONFIG_BROADCOM_BCM4330_WLAN_POWER)       += bcm4330_wlan_power.o

