#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_FIH_KEYBOARD_GPIO)		+= gpio_keys.o
obj-$(CONFIG_KEYBOARD_QWERTY_TCA8418)   += qwerty_tca8418.o
